export const appointments = [
  {
    id: "1",
    tipo: "warning", // Encaixe
    descricao: "Encaixe - Consulta rápida",
    doutor: "Dr. Ana Silva",
    paciente: "Carlos Souza",
    data: "2024-10-12",
    horario: "09:00",
    duracao: 10, // Duração de 10 minutos
    razao: "Dor de cabeça",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Paciente relatando dor de cabeça leve há 3 dias.",
  },
  {
    id: "2",
    tipo: "success", // success regular
    descricao: "Consulta de rotina",
    doutor: "Dr. Paulo Godoy",
    paciente: "Maria Santos",
    data: "2024-10-07",
    horario: "10:00",
    duracao: 60, // Duração de 1 hora
    razao: "Consulta de rotina",
    planoDeSaude: "Unimed",
    anexos: [],
    observations: "Paciente com consulta regular para revisão de saúde.",
  },
  {
    id: "3",
    tipo: "error", // Cancelado
    descricao: "Consulta cancelada",
    doutor: "Dr. Alice",
    paciente: "João Oliveira",
    data: "2024-10-09",
    horario: "11:00",
    duracao: 45, // Duração de 45 minutos
    razao: "Consulta de rotina",
    planoDeSaude: "Bradesco",
    anexos: [],
    observations: "Consulta cancelada pelo paciente.",
  },
  {
    id: "4",
    tipo: "success",
    descricao: "Consulta de retorno",
    doutor: "Dr. Paulo Godoy",
    paciente: "Luiza Almeida",
    data: "2024-10-12",
    horario: "12:00",
    duracao: 30, // Duração de 30 minutos
    razao: "Retorno após cirurgia",
    planoDeSaude: "Unimed",
    anexos: ["relatorio-cirurgia.pdf"],
    observations: "Retorno pós-operatório para avaliação de recuperação.",
  },
  {
    id: "5",
    tipo: "warning", // Encaixe
    descricao: "Encaixe - Urgência leve",
    doutor: "Dr. Ana Silva",
    paciente: "Ricardo Pereira",
    data: "2024-10-14",
    horario: "13:00",
    duracao: 20, // Duração de 20 minutos
    razao: "Febre leve",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Paciente relatando febre moderada e dor muscular.",
  },
  {
    id: "6",
    tipo: "success",
    descricao: "Consulta de rotina",
    doutor: "Dr. Paulo Godoy",
    paciente: "Roberta Lima",
    data: "2024-10-15",
    horario: "14:00",
    duracao: 60, // Duração de 1 hora
    razao: "Consulta de rotina",
    planoDeSaude: "Unimed",
    anexos: [],
    observations: "Consulta regular para check-up geral.",
  },
  {
    id: "7",
    tipo: "error", // Cancelado
    descricao: "Consulta cancelada",
    doutor: "Dr. Alice",
    paciente: "André Silva",
    data: "2024-10-18",
    horario: "15:00",
    duracao: 25, // Duração de 25 minutos
    razao: "Dor de garganta",
    planoDeSaude: "SulAmérica",
    anexos: [],
    observations: "Consulta cancelada pelo paciente no dia anterior.",
  },
  {
    id: "8",
    tipo: "success",
    descricao: "Consulta pediátrica",
    doutor: "Dr. Paulo Godoy",
    paciente: "Gabriel Ferreira",
    data: "2024-10-20",
    horario: "16:00",
    duracao: 80, // Duração de 45 minutos
    razao: "Avaliação pediátrica",
    planoDeSaude: "Bradesco",
    anexos: [],
    observations: "Primeira consulta pediátrica para avaliação geral.",
  },
  {
    id: "9",
    tipo: "success",
    descricao: "Consulta de retorno",
    doutor: "Dr. Alice",
    paciente: "Renata Almeida",
    data: "2024-10-23",
    horario: "17:00",
    duracao: 35, // Duração de 35 minutos
    razao: "Revisão pós-operatória",
    planoDeSaude: "Unimed",
    anexos: ["exames-pos-op.pdf"],
    observations: "Retorno após cirurgia realizada há 3 semanas.",
  },
  {
    id: "10",
    tipo: "warning", // Encaixe
    descricao: "Encaixe - Avaliação rápida",
    doutor: "Dr. Ana Silva",
    paciente: "Lucas Mendes",
    data: "2024-10-25",
    horario: "18:00",
    duracao: 15, // Duração de 15 minutos
    razao: "Avaliação de sintomas leves",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Paciente com sintomas leves de resfriado.",
  },
  {
    id: "11",
    tipo: "success",
    descricao: "Consulta de rotina",
    doutor: "Dr. Paula Azevedo",
    paciente: "Juliana Souza",
    data: "2024-10-15",
    horario: "09:00",
    duracao: 60, // Duração de 1 hora
    razao: "Consulta de rotina",
    planoDeSaude: "Unimed",
    anexos: [],
    observations: "Consulta regular para check-up.",
  },
  {
    id: "12",
    tipo: "error", // Cancelado
    descricao: "Consulta cancelada",
    doutor: "Dr. Alice",
    paciente: "Henrique Alves",
    data: "2024-10-15",
    horario: "10:00",
    duracao: 40, // Duração de 40 minutos
    razao: "Dor no joelho",
    planoDeSaude: "Bradesco",
    anexos: [],
    observations: "Consulta cancelada pelo paciente.",
  },
  {
    id: "13",
    tipo: "success",
    descricao: "Consulta de retorno",
    doutor: "Dr. Paulo Godoy",
    paciente: "Ana Costa",
    data: "2024-10-15",
    horario: "10:00",
    duracao: 35, // Duração de 35 minutos
    razao: "Revisão pós-operatória",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Retorno pós-cirurgia.",
  },
  {
    id: "14",
    tipo: "success",
    descricao: "Consulta de rotina",
    doutor: "Dr. Paulo Godoy",
    paciente: "Paulo Santos",
    data: "2024-11-05",
    horario: "12:30",
    duracao: 45, // Duração de 45 minutos
    razao: "Check-up",
    planoDeSaude: "SulAmérica",
    anexos: [],
    observations: "Consulta de rotina.",
  },
  {
    id: "15",
    tipo: "warning", // Encaixe
    descricao: "Encaixe - Consulta rápida",
    doutor: "Dr. Ana Silva",
    paciente: "Mariana Costa",
    data: "2024-11-06",
    horario: "13:00",
    duracao: 10, // Duração de 10 minutos
    razao: "Dor nas costas",
    planoDeSaude: "Bradesco",
    anexos: [],
    observations: "Paciente com dor lombar leve.",
  },
  {
    id: "16",
    tipo: "success",
    descricao: "Consulta de retorno",
    doutor: "Dr. Alice",
    paciente: "Eduardo Alves",
    data: "2024-11-08",
    horario: "14:00",
    duracao: 50, // Duração de 50 minutos
    razao: "Retorno após tratamento",
    planoDeSaude: "Unimed",
    anexos: [],
    observations: "Retorno após tratamento para verificar progresso.",
  },
  {
    id: "17",
    tipo: "success",
    descricao: "Consulta de rotina",
    doutor: "Dr. Paulo Godoy",
    paciente: "Mariana Santos",
    data: "2024-11-10",
    horario: "15:00",
    duracao: 60, // Duração de 1 hora
    razao: "Consulta geral",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Consulta de rotina para check-up geral.",
  },
  {
    id: "18",
    tipo: "error", // Cancelado
    descricao: "Consulta cancelada",
    doutor: "Dr. Ana Silva",
    paciente: "Lucas Rocha",
    data: "2024-11-12",
    horario: "16:00",
    duracao: 25, // Duração de 25 minutos
    razao: "Dor de cabeça",
    planoDeSaude: "SulAmérica",
    anexos: [],
    observations: "Consulta cancelada pelo paciente.",
  },
  {
    id: "19",
    tipo: "warning", // Encaixe
    descricao: "Encaixe - Avaliação rápida",
    doutor: "Dr. Paulo Godoy",
    paciente: "Thiago Lima",
    data: "2024-11-14",
    horario: "17:00",
    duracao: 15, // Duração de 15 minutos
    razao: "Dor no peito",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Paciente com dor torácica leve. Avaliação rápida.",
  },
  {
    id: "20",
    tipo: "success",
    descricao: "Consulta de rotina",
    doutor: "Dr. Alice",
    paciente: "Ana Lima",
    data: "2024-11-16",
    horario: "18:00",
    duracao: 60, // Duração de 1 hora
    razao: "Consulta geral",
    planoDeSaude: "Unimed",
    anexos: [],
    observations: "Consulta de rotina para check-up.",
  },
  {
    id: "21",
    tipo: "success",
    descricao: "Consulta de rotina",
    doutor: "Dr. Paulo Godoy",
    paciente: "Mateus Oliveira",
    data: "2024-10-03",
    horario: "09:00",
    duracao: 50, // Duração de 50 minutos
    razao: "Consulta de rotina",
    planoDeSaude: "Amil",
    anexos: [],
    observations: "Paciente com consulta de rotina para revisão.",
  },
  // Continue adicionando durações semelhantes para os demais agendamentos
];
